# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('itemID', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('bs', models.BooleanField()),
                ('itemID', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currentLiquid', models.IntegerField()),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='watchedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userWatched', models.BooleanField()),
                ('machineWatched', models.BooleanField()),
                ('itemID', models.IntegerField()),
            ],
        ),
    ]
