# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commandsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('bs', models.BooleanField()),
                ('itemID', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
