# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_commandsdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondata',
            name='completed',
        ),
    ]
